/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.FontMetrics;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import uteis.Uteis;
import modelo.dao.CategoriaDao;
import modelo.dao.ItemVendaDao;
import modelo.dao.MarcaDao;
import modelo.dao.ProdutoDao;
import modelo.dao.VendaDao;
import modelo.entidade.Categoria;
import modelo.entidade.Cliente;
import modelo.entidade.ItemVenda;
import modelo.entidade.Marca;
import modelo.entidade.Produto;
import modelo.entidade.Venda;
import visao.TableModel.ListaVendaTableModel;
import visao.TableModel.ProdutoColumnModel;
import visao.TableModel.ProdutoTableModel;
import visao.TableModel.ListaVendaColumnModel;

/**
 *
 * @author Diogo
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.carregarComboBoxCategoria();
        this.carregarComboBoxMarca();
        this.jComboParamCategoria.setEnabled(false);
        this.jComboParamMarca.setEnabled(false);
        this.jBtnAdicionarProduto.setEnabled(false);
        this.jBtnRemoverProduto.setEnabled(false);
        this.jBtnFinalizarCompra.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGpBtnTipoPagamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTxfPesquisarProduto = new javax.swing.JTextField();
        jComboParamProduto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboParamMarca = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboParamCategoria = new javax.swing.JComboBox<>();
        jBtnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblBuscarProdutos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTxfEstoque = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxfCategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxfMarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxfNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxfCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxfValorUnit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxfValorTotal = new javax.swing.JTextField();
        jBtnAdicionarProduto = new javax.swing.JButton();
        jSpnQuantidade = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblListaVenda = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jBtnRemoverProduto = new javax.swing.JButton();
        jBtnFinalizarCompra = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jTxfNomeCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jBtnSelecionarCliente = new javax.swing.JButton();
        jRadioBtnAVista = new javax.swing.JRadioButton();
        jRadioBtnCartaoDebito = new javax.swing.JRadioButton();
        jRadioBtnCartaoCredito = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioBtnCheque = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTxfValorTotalCompra = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxfCpfCliente = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnProduto = new javax.swing.JMenuItem();
        jMnMarca = new javax.swing.JMenuItem();
        jMnCategoria = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnCliente = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MK-Commerce");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Produtos"));

        jTxfPesquisarProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboParamProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboParamProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Marca", "Categoria" }));
        jComboParamProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboParamProdutoItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Marca");

        jComboParamMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboParamMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Categoria");

        jComboParamCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboParamCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setToolTipText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTblBuscarProdutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTblBuscarProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Nome", "Marca", "Categoria", "Preço", "Estoque", "Estoque Mínimo"
            }
        ));
        jTblBuscarProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblBuscarProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblBuscarProdutos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTxfEstoque.setEditable(false);
        jTxfEstoque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Estoque");

        jTxfCategoria.setEditable(false);
        jTxfCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Categoria");

        jTxfMarca.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Marca");

        jTxfNome.setEditable(false);
        jTxfNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nome");

        jTxfCodigo.setEditable(false);
        jTxfCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Código");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Valor Unitário");

        jTxfValorUnit.setEditable(false);
        jTxfValorUnit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Quantidade");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Valor Total");

        jTxfValorTotal.setEditable(false);
        jTxfValorTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jBtnAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/shopping-basket-add.png"))); // NOI18N
        jBtnAdicionarProduto.setToolTipText("Adicionar Produto");
        jBtnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarProdutoActionPerformed(evt);
            }
        });

        jSpnQuantidade.setFont(new java.awt.Font("Tahoma", 0, 12));
        jSpnQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpnQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpnQuantidadeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpnQuantidade)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAdicionarProduto)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBtnAdicionarProduto)
                    .addComponent(jTxfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jTxfValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTxfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTxfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jSpnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboParamProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxfPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboParamMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboParamCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboParamProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jComboParamMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jComboParamCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos"));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTblListaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Códgo", "Nome", "Marca", "Categoria", "Valor Unitário", "Quantidade", "Valor Total"
            }
        ));
        jTblListaVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblListaVendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblListaVenda);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnRemoverProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/shopping-basket-remove.png"))); // NOI18N
        jBtnRemoverProduto.setToolTipText("Remover Produto");
        jBtnRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverProdutoActionPerformed(evt);
            }
        });

        jBtnFinalizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/shopping-basket-accept.png"))); // NOI18N
        jBtnFinalizarCompra.setToolTipText("Finalizar Compra");
        jBtnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFinalizarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnRemoverProduto)
                    .addComponent(jBtnFinalizarCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jBtnRemoverProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jBtnFinalizarCompra)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes da Venda"));

        jTxfNomeCliente.setEditable(false);
        jTxfNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxfNomeCliente.setVerifyInputWhenFocusTarget(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Cliente");
        jLabel11.setToolTipText("");

        jBtnSelecionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/novo.png"))); // NOI18N
        jBtnSelecionarCliente.setToolTipText("Adicionar Cliente");
        jBtnSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelecionarClienteActionPerformed(evt);
            }
        });

        jGpBtnTipoPagamento.add(jRadioBtnAVista);
        jRadioBtnAVista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioBtnAVista.setText("À Vista");

        jGpBtnTipoPagamento.add(jRadioBtnCartaoDebito);
        jRadioBtnCartaoDebito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioBtnCartaoDebito.setText("Cartão de Débito");

        jGpBtnTipoPagamento.add(jRadioBtnCartaoCredito);
        jRadioBtnCartaoCredito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioBtnCartaoCredito.setText("Cartão de Crédito");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Tipo de Pagamento");

        jGpBtnTipoPagamento.add(jRadioBtnCheque);
        jRadioBtnCheque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioBtnCheque.setText("Cheque");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Valor Total");

        jTxfValorTotalCompra.setEditable(false);
        jTxfValorTotalCompra.setText("0.00");

        jLabel14.setText("CPF");

        jTxfCpfCliente.setEditable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxfNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxfCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(jBtnSelecionarCliente))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxfValorTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBtnCartaoCredito)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBtnCartaoDebito)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBtnAVista)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBtnCheque))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBtnSelecionarCliente)
                    .addComponent(jTxfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jTxfCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBtnCartaoCredito)
                    .addComponent(jRadioBtnCartaoDebito)
                    .addComponent(jRadioBtnAVista)
                    .addComponent(jLabel12)
                    .addComponent(jRadioBtnCheque)
                    .addComponent(jLabel13)
                    .addComponent(jTxfValorTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setName(""); // NOI18N

        jMenu1.setMnemonic('C');
        jMenu1.setText("Consulta e Cadastro");
        jMenu1.setToolTipText("");

        jMnProduto.setMnemonic('P');
        jMnProduto.setText("Produto");
        jMnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMnProduto);

        jMnMarca.setMnemonic('M');
        jMnMarca.setText("Marca");
        jMnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnMarcaActionPerformed(evt);
            }
        });
        jMenu1.add(jMnMarca);

        jMnCategoria.setMnemonic('C');
        jMnCategoria.setText("Categoria");
        jMnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(jMnCategoria);
        jMenu1.add(jSeparator1);

        jMnCliente.setMnemonic('C');
        jMnCliente.setText("Cliente");
        jMnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMnCliente);
        jMenu1.add(jSeparator3);

        jMenuItem1.setMnemonic('V');
        jMenuItem1.setText("Vendas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnProdutoActionPerformed
        new ProdutoCons(this, true).setVisible(true);
    }//GEN-LAST:event_jMnProdutoActionPerformed

    private void jMnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnCategoriaActionPerformed
        new CategoriaCons(this, true).setVisible(true);
    }//GEN-LAST:event_jMnCategoriaActionPerformed

    private void jMnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnClienteActionPerformed
        new ClienteCons(this, true).setVisible(true);
    }//GEN-LAST:event_jMnClienteActionPerformed

    private void jMnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnMarcaActionPerformed
        new MarcaCons(this, true).setVisible(true);
    }//GEN-LAST:event_jMnMarcaActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        botaoPesquisarProduto();
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jComboParamProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboParamProdutoItemStateChanged
        if (jComboParamProduto.getSelectedItem().toString().equals("Categoria")) {
            jComboParamCategoria.setEnabled(true);
            jComboParamMarca.setEnabled(false);
            jTxfPesquisarProduto.setEnabled(false);
        } else if (jComboParamProduto.getSelectedItem().toString().equals("Marca")) {
            jComboParamCategoria.setEnabled(false);
            jComboParamMarca.setEnabled(true);
            jTxfPesquisarProduto.setEnabled(false);
        } else {
            jComboParamCategoria.setEnabled(false);
            jComboParamMarca.setEnabled(false);
            jTxfPesquisarProduto.setEnabled(true);
        }
    }//GEN-LAST:event_jComboParamProdutoItemStateChanged

    private void jTblBuscarProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblBuscarProdutosMouseClicked
        this.jBtnAdicionarProduto.setEnabled(true);
        this.mostrarProdutoSelecionado();
    }//GEN-LAST:event_jTblBuscarProdutosMouseClicked

    private void jSpnQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpnQuantidadeStateChanged
        double valorTotal = getProdutoSelecionado().getPreco() * (int)jSpnQuantidade.getValue();
        jTxfValorTotal.setText(Uteis.stringFormat(valorTotal));
    }//GEN-LAST:event_jSpnQuantidadeStateChanged

    private void jBtnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarProdutoActionPerformed
        this.adicionarProdutoListaVenda();
        jBtnFinalizarCompra.setEnabled(true);
    }//GEN-LAST:event_jBtnAdicionarProdutoActionPerformed

    private void jBtnSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelecionarClienteActionPerformed
        this.botaoSelecionarCliente();
    }//GEN-LAST:event_jBtnSelecionarClienteActionPerformed

    private void jBtnRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverProdutoActionPerformed
        this.botaoRemoverProduto();
    }//GEN-LAST:event_jBtnRemoverProdutoActionPerformed

    private void jTblListaVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblListaVendaMouseClicked
        int ls = jTblListaVenda.getSelectedRow();
        
        if (ls >= 0) {
            jBtnRemoverProduto.setEnabled(true);
        }
    }//GEN-LAST:event_jTblListaVendaMouseClicked

    private void jBtnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFinalizarCompraActionPerformed
        this.finalizarCompra();
    }//GEN-LAST:event_jBtnFinalizarCompraActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new VendaCons(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja receber um relátorio dos prrodutos no estoque?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                new ChecarEstoqueCons(this, true).setVisible(true);
            } else {
            System.exit(0);
            }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionarProduto;
    private javax.swing.JButton jBtnFinalizarCompra;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JButton jBtnRemoverProduto;
    private javax.swing.JButton jBtnSelecionarCliente;
    private javax.swing.JComboBox<String> jComboParamCategoria;
    private javax.swing.JComboBox<String> jComboParamMarca;
    private javax.swing.JComboBox<String> jComboParamProduto;
    private javax.swing.ButtonGroup jGpBtnTipoPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMnCategoria;
    private javax.swing.JMenuItem jMnCliente;
    private javax.swing.JMenuItem jMnMarca;
    private javax.swing.JMenuItem jMnProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioBtnAVista;
    private javax.swing.JRadioButton jRadioBtnCartaoCredito;
    private javax.swing.JRadioButton jRadioBtnCartaoDebito;
    private javax.swing.JRadioButton jRadioBtnCheque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSpinner jSpnQuantidade;
    private javax.swing.JTable jTblBuscarProdutos;
    private javax.swing.JTable jTblListaVenda;
    private javax.swing.JTextField jTxfCategoria;
    private javax.swing.JTextField jTxfCodigo;
    private javax.swing.JTextField jTxfCpfCliente;
    private javax.swing.JTextField jTxfEstoque;
    private javax.swing.JTextField jTxfMarca;
    private javax.swing.JTextField jTxfNome;
    private javax.swing.JTextField jTxfNomeCliente;
    private javax.swing.JTextField jTxfPesquisarProduto;
    private javax.swing.JTextField jTxfValorTotal;
    private javax.swing.JTextField jTxfValorTotalCompra;
    private javax.swing.JTextField jTxfValorUnit;
    // End of variables declaration//GEN-END:variables

    private List<Produto> listaProduto;
    private List<Venda> listaVenda = new ArrayList<>();
    private Venda venda;
    private VendaDao vendaDao;
    private ItemVenda itemVenda;
    private ItemVendaDao itemVendaDao;
    private Produto produto;
    private ProdutoDao produtoDao;
    private MarcaDao marcaDao;
    private CategoriaDao categoriaDao;
    private Cliente cliente;
    private double valorTotalCompra = 0;
  
    /*
    // Buscar Produtos 
     */
    private DefaultComboBoxModel comboBoxMarca;
    private DefaultComboBoxModel comboBoxCategoria;

    private void carregarComboBoxMarca() {
        if (marcaDao == null) {
            marcaDao = new MarcaDao();
        }
        List<Marca> listaMarca = marcaDao.pesquisar("");
        comboBoxMarca = (DefaultComboBoxModel) jComboParamMarca.getModel();
        comboBoxMarca.removeAllElements();
        for (int linha = 0; linha < listaMarca.size(); linha++) {
            Marca marca = listaMarca.get(linha);
            comboBoxMarca.addElement(marca);
        }
        jComboParamMarca.setModel(comboBoxMarca);
    }

    private void carregarComboBoxCategoria() {
        if (categoriaDao == null) {
            categoriaDao = new CategoriaDao();
        }
        List<Categoria> listaCategoria = categoriaDao.pesquisar("");
        comboBoxCategoria = (DefaultComboBoxModel) jComboParamCategoria.getModel();
        comboBoxCategoria.removeAllElements();
        for (int linha = 0; linha < listaCategoria.size(); linha++) {
            Categoria categoria = listaCategoria.get(linha);
            comboBoxCategoria.addElement(categoria);
        }
        jComboParamCategoria.setModel(comboBoxCategoria);
 
    }

    private void formatarColumnTableProduto() {
        FontMetrics fm = jTblBuscarProdutos.getFontMetrics(jTblBuscarProdutos.getFont());
        jTblBuscarProdutos.setColumnModel(new ProdutoColumnModel(fm));
    }

    private ProdutoTableModel modeloProduto = new ProdutoTableModel();
    private void setListaProduto(List<Produto> listaProduto) {
        jTblBuscarProdutos.setModel(modeloProduto);
        modeloProduto.addListaDeProduto(listaProduto);
        this.formatarColumnTableProduto();
    }

    private Produto getProdutoSelecionado() {
        return modeloProduto.getProduto(jTblBuscarProdutos.getSelectedRow());
    }

    private void mostrarProdutoSelecionado() {
        jTxfCodigo.setText(getProdutoSelecionado().getCodProduto().toString());
        jTxfNome.setText(getProdutoSelecionado().getNome());
        jTxfMarca.setText(getProdutoSelecionado().getMarca().getNome());
        jTxfCategoria.setText(getProdutoSelecionado().getCategoria().getNome());
        jTxfEstoque.setText(getProdutoSelecionado().getQtdeEstoque().toString());
        jTxfValorUnit.setText(Float.toString(getProdutoSelecionado().getPreco()));
        jTxfValorTotal.setText(Float.toString(getProdutoSelecionado().getPreco()));
        jSpnQuantidade.setValue(1);
    }

    String paramProduto[] = new String[4];

    private void getParametroPesquisaProduto() {
        paramProduto[0] = jComboParamProduto.getSelectedItem().toString().toUpperCase();
        paramProduto[1] = jTxfPesquisarProduto.getText().toUpperCase();
        paramProduto[2] = jComboParamMarca.getSelectedItem().toString().toUpperCase();
        paramProduto[3] = jComboParamCategoria.getSelectedItem().toString().toUpperCase();
    }

    private void botaoPesquisarProduto() {
        getParametroPesquisaProduto();
        if (produtoDao == null) {
            produtoDao = new ProdutoDao();
        }
        List<Produto> listaProduto = new ArrayList<>();

        if (paramProduto[0].equals("CÓDIGO")) {
            listaProduto.add(produtoDao.selectCod(Integer.parseInt(paramProduto[1])));
        } else if (paramProduto[0].equals("NOME")) {
            listaProduto = produtoDao.selectNome(paramProduto[1]);
        } else if (paramProduto[0].equals("MARCA")) {
            Marca marca = marcaDao.buscarMarca(paramProduto[2]);
            listaProduto = produtoDao.selectMarca(marca.getId());
        } else {
            Categoria categoria = categoriaDao.buscarCategoria(paramProduto[3]);
            listaProduto = produtoDao.selectCategoria(categoria.getId());
        }
        setListaProduto(listaProduto);
    }
    
    //Selecionar Cliente
    private void botaoSelecionarCliente() {
        BuscarClienteCons buscarCliente = new BuscarClienteCons(this, true);
        buscarCliente.setVisible(true); 
        cliente = new Cliente();
        cliente = buscarCliente.getCliente();
        jTxfNomeCliente.setText(cliente.getNome());
        jTxfCpfCliente.setText(cliente.getCpf());
    }
    
    //Lista de Produtos
    private void formatarColumnTableListaVenda() {
        FontMetrics fm = jTblListaVenda.getFontMetrics(jTblListaVenda.getFont());
        jTblListaVenda.setColumnModel(new ListaVendaColumnModel(fm));
    }
    
    private Venda getProdutoSelecionadoListaVenda() {
        return modeloVenda.getVenda(jTblListaVenda.getSelectedRow());
    }
    
    private ListaVendaTableModel modeloVenda = new ListaVendaTableModel();
    private void setListaVenda(List<Venda> listaVenda) {
        jTblListaVenda.setModel(modeloVenda);
        modeloVenda.addListaDeVenda(listaVenda);
        formatarColumnTableListaVenda();
    }

    private void adicionarProdutoListaVenda() {
        if ((int)jSpnQuantidade.getValue() < getProdutoSelecionado().getQtdeEstoque()) {
            venda = new Venda();
            venda.setIdProduto(getProdutoSelecionado().getId());
            venda.setCodProduto(getProdutoSelecionado().getCodProduto());
            venda.setProduto(getProdutoSelecionado());
            venda.setMarcaProduto(getProdutoSelecionado().getMarca());
            venda.setCategoriaProduto(getProdutoSelecionado().getCategoria());
            venda.setQtdeEstoque(getProdutoSelecionado().getQtdeEstoque());
            venda.setValorUnitario(getProdutoSelecionado().getPreco());
            venda.setQuantidade((int) jSpnQuantidade.getValue());
            double valorTotal = getProdutoSelecionado().getPreco() * (int)jSpnQuantidade.getValue();
            String strValorTotal = Uteis.formatarDecimal(valorTotal, 2);
            double valorTotalFormatado = Uteis.formatarDecimal(strValorTotal);
            venda.setValorTotal(valorTotalFormatado);
            
            valorTotalCompra += valorTotal;
            jTxfValorTotalCompra.setText(Uteis.stringFormat(valorTotalCompra));
            
            listaVenda.add(venda);
            setListaVenda(listaVenda);
        } else {
            JOptionPane.showMessageDialog(null, "A quantidade de PRODUTOS excede a quantidade no ESTOQUE!");
        }
    }
    
    private void removerProdutoListaVenda() {
        listaVenda.remove(jTblListaVenda.getSelectedRow());
        formatarColumnTableListaVenda();
    }
    
    private void botaoRemoverProduto() {
        double valorTotal = getProdutoSelecionadoListaVenda().getValorTotal();
        valorTotalCompra = valorTotalCompra - valorTotal;
        jTxfValorTotalCompra.setText(Uteis.stringFormat(valorTotalCompra));
        
        this.removerProdutoListaVenda();
        
        if (listaVenda.isEmpty()) {
            jBtnRemoverProduto.setEnabled(false);
            jBtnFinalizarCompra.setEnabled(false);
        } else {
            jBtnFinalizarCompra.setEnabled(true);
        }
    }
    
    private void limparDadosTela() {
        jComboParamProduto.setSelectedIndex(1);
        jTxfPesquisarProduto.setText("");
        carregarComboBoxCategoria();
        carregarComboBoxMarca();
        listaProduto = new ArrayList<>();
        setListaProduto(listaProduto);
        jTxfCodigo.setText("");
        jTxfNome.setText("");
        jTxfMarca.setText("");
        jTxfCategoria.setText("");
        jTxfEstoque.setText("");
        jTxfValorUnit.setText("");
        jSpnQuantidade.setValue(1);
        jTxfValorTotal.setText("");
        cliente = new Cliente();
        jTxfNomeCliente.setText("");
        jTxfCpfCliente.setText("");
        jTxfValorTotalCompra.setText("0.00");
        jGpBtnTipoPagamento.clearSelection();
        listaVenda = new ArrayList<>();
        setListaVenda(listaVenda);
    }
    
    private void finalizarCompra() {
        if (jGpBtnTipoPagamento.getSelection() != null && cliente != null) {
            venda = new Venda();
            venda.setCliente(cliente);
            venda.setTipoPagamento(getTextBotaoSelecionado(jGpBtnTipoPagamento));
            venda.setDataVenda(new Date());
            
            vendaDao = new VendaDao();
            vendaDao.insertVenda(venda);
            for (int i = 0; i < listaVenda.size(); i++) {
                itemVenda = new ItemVenda();
                itemVenda.setId_venda(vendaDao.selectUltimaVenda());
                itemVenda.setProduto(listaVenda.get(i).getProduto());
                itemVenda.setQuantidade(listaVenda.get(i).getQuantidade());
                itemVenda.setValorUnitario(listaVenda.get(i).getValorUnitario());
                
                itemVendaDao = new ItemVendaDao();
                itemVendaDao.insertItemVenda(itemVenda);
                
                produtoDao = new ProdutoDao();
                int estoqueAtualizado = listaVenda.get(i).getQtdeEstoque()- listaVenda.get(i).getQuantidade();
                produtoDao.updateEstoque(listaVenda.get(i).getIdProduto(), estoqueAtualizado);
            }
            JOptionPane.showMessageDialog(null, "Compra realizada com sucesso!");
            limparDadosTela();
        } else {
            JOptionPane.showMessageDialog(null, "Informe os DETALHES DA VENDA! ");
        }
    }
    
    public static String getTextBotaoSelecionado(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    
}
