/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.dao.CategoriaDao;
import modelo.dao.MarcaDao;
import modelo.dao.ProdutoDao;
import modelo.entidade.Categoria;
import modelo.entidade.Marca;
import modelo.entidade.Produto;

/**
 *
 * @author Diogo
 */
public class ProdutoFrm extends javax.swing.JDialog {

    /**
     * Creates new form ProdutoFrm
     */
    public ProdutoFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciarForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxfId = new javax.swing.JTextField();
        jTxfCodigo = new javax.swing.JTextField();
        jTxfNome = new javax.swing.JTextField();
        jComboMarca = new javax.swing.JComboBox<>();
        jComboCategoria = new javax.swing.JComboBox<>();
        jTxfPreco = new javax.swing.JTextField();
        jTxfEstoque = new javax.swing.JTextField();
        jTxfEstoqueMin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnNovo = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formuláro Produtto");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Marca");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Categoria");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Preço");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Estoque");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Estoque Mín");

        jTxfId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxfCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxfNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxfPreco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxfEstoque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxfEstoqueMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxfCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jTxfId, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxfEstoqueMin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxfEstoque, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxfPreco, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, 96, Short.MAX_VALUE)
                        .addComponent(jComboMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTxfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxfEstoqueMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/novo.png"))); // NOI18N
        jBtnNovo.setToolTipText("Adicionar");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });

        jBtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/save.png"))); // NOI18N
        jBtnSalvar.setToolTipText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/delete.png"))); // NOI18N
        jBtnExcluir.setToolTipText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/exit.png"))); // NOI18N
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSair)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnSair)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnSalvar)
                    .addComponent(jBtnNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        this.botaoNovo();
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        this.botaoSalvar();
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        this.botaoExcluir();
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProdutoFrm dialog = new ProdutoFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JComboBox<String> jComboCategoria;
    private javax.swing.JComboBox<String> jComboMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxfCodigo;
    private javax.swing.JTextField jTxfEstoque;
    private javax.swing.JTextField jTxfEstoqueMin;
    private javax.swing.JTextField jTxfId;
    private javax.swing.JTextField jTxfNome;
    private javax.swing.JTextField jTxfPreco;
    // End of variables declaration//GEN-END:variables
    
    private Produto produto;
    private ProdutoDao produtoDao;
    private Marca marca;
    private MarcaDao marcaDao;
    private Categoria categoria;
    private CategoriaDao categoriaDao;
    
    //ComboBox Marca 
    private DefaultComboBoxModel comboBoxMarca;
    private DefaultComboBoxModel comboBoxCategoria;
    
    private void carregarComboBoxMarca() {
        if (marcaDao == null) {
            marcaDao = new MarcaDao();
        }
        List<Marca> listaMarca = marcaDao.selectNome("");
        comboBoxMarca = (DefaultComboBoxModel)jComboMarca.getModel();
        comboBoxMarca.removeAllElements();
        for (int linha = 0; linha < listaMarca.size(); linha++) {
            Marca marca = listaMarca.get(linha);
            comboBoxMarca.addElement(marca);
        }
        jComboMarca.setModel(comboBoxMarca);
    }
    
    private Marca getMarcaSelecionada() {
        return (Marca)jComboMarca.getSelectedItem();
    }
    
    //ComboBoxCategoria
    private void carregarComboBoxCategoria() {
        if (categoriaDao == null) {
            categoriaDao = new CategoriaDao();
        }
        List<Categoria> listaCategoria = categoriaDao.selectNome("");
        comboBoxCategoria = (DefaultComboBoxModel)jComboCategoria.getModel();
        comboBoxCategoria.removeAllElements();
        for (int linha = 0; linha < listaCategoria.size(); linha++) {
            Categoria categoria = listaCategoria.get(linha);
            comboBoxCategoria.addElement(categoria);
        }
        jComboCategoria.setModel(comboBoxCategoria);
    }
    
    private Categoria getCategoriaSelecionada() {
        return (Categoria)jComboCategoria.getSelectedItem();
    }
    
    private void iniciarForm() {
        produto = new Produto();
        this.carregarComboBoxCategoria();
        this.carregarComboBoxMarca();
        jBtnNovo.setEnabled(false);
        jBtnSalvar.setEnabled(true);
        jBtnExcluir.setEnabled(false);
        jTxfId.setEditable(false);
    }
    
    private void mostrarDadosForm() {
        this.carregarComboBoxCategoria();
        this.carregarComboBoxMarca();
        if (produto != null) {
            if (produto.getId() != null) {
                jTxfId.setText(produto.getId().toString());
            } else {
                jTxfId.setText("");
            }
            if (marca != null && categoria != null) {
            jComboMarca.setSelectedItem(marca.getNome());
            jComboCategoria.setSelectedItem(categoria.getNome());
            jTxfCodigo.setText(Integer.toString(produto.getCodProduto()));
            jTxfNome.setText(produto.getNome());
            jTxfPreco.setText(Float.toString(produto.getPreco()));
            jTxfEstoque.setText(Integer.toString(produto.getQtdeEstoque()));
            jTxfEstoqueMin.setText(Integer.toString(produto.getEstoqueMin()));
            }
        } else {
            this.limparDadosFrom();
        }
        
        if (produto.getId() != null) {
            jBtnNovo.setEnabled(true);
            jBtnSalvar.setEnabled(true);
            jBtnExcluir.setEnabled(true);
        } else {
            jBtnNovo.setEnabled(false);
            jBtnSalvar.setEnabled(true);
            jBtnExcluir.setEnabled(false);
        }
    }
    
    private void limparDadosFrom() {
        jTxfId.setText("");
        jTxfCodigo.setText("");
        jTxfNome.setText("");
        carregarComboBoxMarca();
        carregarComboBoxCategoria();
        jTxfPreco.setText("");
        jTxfEstoque.setText("");
        jTxfEstoqueMin.setText("");
    }
        
    private void obterDadosForm() {
        produto.setCodProduto(Integer.parseInt(jTxfCodigo.getText()));
        produto.setNome(jTxfNome.getText());
        produto.setMarca(getMarcaSelecionada());
        produto.setCategoria(getCategoriaSelecionada());
        produto.setPreco(Float.parseFloat(jTxfPreco.getText()));
        produto.setQtdeEstoque(Integer.parseInt(jTxfEstoque.getText()));
        produto.setEstoqueMin(Integer.parseInt(jTxfEstoqueMin.getText()));
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
        this.mostrarDadosForm();
    }
    
    private void botaoNovo() {
        produto = new Produto();
        jBtnNovo.setEnabled(false);
        jBtnSalvar.setEnabled(true);
        jBtnExcluir.setEnabled(false);
        this.mostrarDadosForm();
    }
    
    private void botaoSalvar() {
        if (produtoDao == null) {
            produtoDao = new ProdutoDao();
        }
        obterDadosForm();
        if (produto.getCodProduto() == null) {
            JOptionPane.showMessageDialog(null, "Insira o código do Produto!");
        } else if(produto.getNome() == null || produto.getNome().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira o nome do Produto!");
        } else if(produto.getMarca() == null || produto.getMarca().getNome().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira a marca do Produto!");
        } else if(produto.getCategoria() == null || produto.getCategoria().getNome().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira a categoria do Produto!");
        } else if(produto.getPreco() == null) {
            JOptionPane.showMessageDialog(null, "Insira o preço do Produto!");
        } else if(produto.getQtdeEstoque() == null || produto.getQtdeEstoque().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira a quantidade de estoque do Produto!");
        } else if(produto.getEstoqueMin() == null || produto.getEstoqueMin().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira o estoque mínimo do Produto!");
        } else {
            produtoDao.salvar(produto);
            botaoNovo();
        }
    }
    
    private void botaoExcluir() {
        if (produtoDao == null) {
            produtoDao = new ProdutoDao();
        }
        produtoDao.excluir(produto);
        
        jBtnNovo.setEnabled(false);
        jBtnSalvar.setEnabled(true);
        jBtnExcluir.setEnabled(false);
        
        produto = new Produto();
        limparDadosFrom();
    }
}
