/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import java.awt.FontMetrics;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.dao.ItemVendaDao;
import modelo.dao.VendaDao;
import modelo.entidade.Cliente;
import modelo.entidade.ItemVenda;
import modelo.entidade.Venda;
import visao.TableModel.ItemVendaColumnModel;
import visao.TableModel.ItemVendaTableModel;
import visao.TableModel.VendaColumnModel;
import visao.TableModel.VendaTableModel;

/**
 *
 * @author Diogo
 */
public class VendaCons extends javax.swing.JDialog {

    /**
     * Creates new form VendaCons
     */
    public VendaCons(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jTxfPesquisar.setEditable(false);
        this.jDateChooser.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new thiagoventurelli.dateutils.datechooser.DateChooser();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxParam = new javax.swing.JComboBox<>();
        jTxfPesquisar = new javax.swing.JTextField();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnPesquisarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblVenda = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblItemVenda = new javax.swing.JTable();
        jDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta  de Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Venda"));

        jComboBoxParam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Data", "ID" }));
        jComboBoxParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxParamActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/from/pesquisar.png"))); // NOI18N
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnPesquisarCliente.setText("...");
        jBtnPesquisarCliente.setToolTipText("Buscar Cliente");
        jBtnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarClienteActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Venda"));

        jTblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Tipo de Pagamento", "Data"
            }
        ));
        jTblVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblVenda);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));

        jTblItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Venda", "Produto", "Quantidade", "Valor Unitário"
            }
        ));
        jScrollPane2.setViewportView(jTblItemVenda);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        jDateChooser.setToolTipText("Selecionar Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addComponent(jBtnPesquisar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTxfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisarCliente)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jComboBoxParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxParamActionPerformed
        if (jComboBoxParam.getSelectedItem().equals("Cliente")) {
            jTxfPesquisar.setText("");
            jTxfPesquisar.setEditable(false);
            jTxfPesquisar.setEnabled(true);
            jBtnPesquisarCliente.setEnabled(true);
            jDateChooser.setDateFormatString("");
            jDateChooser.setEnabled(false);
        } else if (jComboBoxParam.getSelectedItem().equals("ID")) {
            jTxfPesquisar.setText("");
            jTxfPesquisar.setEnabled(true);
            jTxfPesquisar.setEditable(true);
            jBtnPesquisarCliente.setEnabled(false);
            jDateChooser.setDateFormatString("");
            jDateChooser.setEnabled(false);
        } else {
            jTxfPesquisar.setText("");
            jTxfPesquisar.setEnabled(false);
            jBtnPesquisarCliente.setEnabled(false);
            jDateChooser.setEnabled(true);
        }  
    }//GEN-LAST:event_jComboBoxParamActionPerformed

    private void jBtnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarClienteActionPerformed
        this.botaoBuscarCliente();
    }//GEN-LAST:event_jBtnPesquisarClienteActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        this.botaoPesquisar();
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jTblVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblVendaMouseClicked
        this.buscarItemVenda();
    }//GEN-LAST:event_jTblVendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendaCons dialog = new VendaCons(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private thiagoventurelli.dateutils.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JButton jBtnPesquisarCliente;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBoxParam;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblItemVenda;
    private javax.swing.JTable jTblVenda;
    private javax.swing.JTextField jTxfPesquisar;
    // End of variables declaration//GEN-END:variables

    private Cliente cliente;
    private VendaDao vendaDao;
    private ItemVendaDao itemVendaDao;
    private List<ItemVenda> listaItemVenda;
    
    
    //Buscar Venda
    private void formatarColumnTableVenda() {
        FontMetrics fm = jTblVenda.getFontMetrics(jTblVenda.getFont());
        jTblVenda.setColumnModel(new VendaColumnModel(fm));
    }
    
    private VendaTableModel modelVenda = new VendaTableModel();
    private void setListaVenda(List<Venda> listaVenda) {
        jTblVenda.setModel(modelVenda);
        modelVenda.addListaDeVenda(listaVenda);
        this.formatarColumnTableVenda();
    }
    
    private Venda getVendaSelecionada() {
        return modelVenda.getVenda(jTblVenda.getSelectedRow());
    }
    
    String param[] = new String[3];
    private void getParametrosPesquisa() {
        param[0] = jComboBoxParam.getSelectedItem().toString();
        param[1] = jTxfPesquisar.getText();
    }
    
    private void botaoPesquisar() {
        getParametrosPesquisa();
        if (vendaDao == null) {
            vendaDao = new VendaDao();
        }
        List<Venda> listaVenda = new ArrayList<>();
        
        if (param[0].equals("Cliente")) {
            if (cliente != null) {
                listaVenda = vendaDao.selectCliente(cliente.getId());
            } else {
                JOptionPane.showMessageDialog(null, "Selecione o CLIENTE! ");
            }
        } else if (param[0].equals("ID")) {
            listaVenda.add(vendaDao.selectId(Integer.parseInt(param[1])));
        } else {
            if (jDateChooser.getDate() != null) {
                listaVenda = vendaDao.selectData(jDateChooser.getDate());
            } else {
                JOptionPane.showMessageDialog(null, "Selecione a DATA");
            }
        }
        setListaVenda(listaVenda);
    }
    
    private void botaoBuscarCliente() {
        BuscarClienteCons bc = new BuscarClienteCons(new JFrame(), true);
        bc.setVisible(true);
        cliente = new Cliente();
        cliente = bc.getCliente();
        jTxfPesquisar.setText(cliente.getNome());
    }
    
    //Lista itemVenda
    
    private void formatarColumnTableItemVenda() {
        FontMetrics fm = jTblItemVenda.getFontMetrics(jTblItemVenda.getFont());
        jTblItemVenda.setColumnModel(new ItemVendaColumnModel(fm));
    }
    
    ItemVendaTableModel modelItemVenda = new ItemVendaTableModel();
    public void setListaItemVenda(List<ItemVenda> listaItemVenda) {
        jTblItemVenda.setModel(modelItemVenda);
        modelItemVenda.addListaItemVenda(listaItemVenda);
        this.formatarColumnTableItemVenda();
    }
    
    public void buscarItemVenda() {
        if (itemVendaDao == null) {
            itemVendaDao = new ItemVendaDao();
        }
        listaItemVenda = new ArrayList<>();
        
        listaItemVenda = itemVendaDao.selectId(getVendaSelecionada().getIdVenda());
        setListaItemVenda(listaItemVenda);
    }
}
